import { useState } from 'react'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import { LockKeyhole, Mail, ShieldCheck, UserRound } from 'lucide-react'
import { Brand } from '../components/Brand'
import { SimulationBanner } from '../components/Common'
import { usePulse } from '../context/PulseContext'

export function LoginPage(){
  const { login }=usePulse(); const nav=useNavigate(); const loc=useLocation();
  const [form,setForm]=useState({email:'',password:''}); const [error,setError]=useState('')
  const submit=async e=>{e.preventDefault();const r=await login(form.email,form.password);if(!r.ok)return setError(r.message);nav(['admin','dispatcher'].includes(r.user.role)?'/command':(loc.state?.from||'/app'))}
  const fill=(role)=> setForm(role==='admin'?{email:'admin@pulse.demo',password:'Pulse911!'}:{email:'citizen@pulse.demo',password:'Pulse911!'})
  return <div className="auth-page"><SimulationBanner/><div className="auth-wrap"><div className="auth-info"><Brand light/><span className="eyebrow dark">ACCESO SEGURO DE DEMOSTRACIÓN</span><h1>Accede a PULSE 911</h1><p>Utiliza una cuenta ciudadana o de PULSE Command. Los datos son locales y ficticios.</p><div className="demo-account"><strong>Citizen</strong><span>citizen@pulse.demo</span><button type="button" onClick={()=>fill('citizen')}>Usar cuenta</button></div><div className="demo-account"><strong>Command</strong><span>admin@pulse.demo</span><button type="button" onClick={()=>fill('admin')}>Usar cuenta</button></div><small>Contraseña de ambas: <b>Pulse911!</b></small></div><form className="auth-card" onSubmit={submit}><div className="auth-icon"><ShieldCheck/></div><h2>Iniciar sesión</h2><p>Continúa al portal correspondiente a tu rol.</p>{error&&<div className="form-error" role="alert">{error}</div>}<label>Correo<div className="input-icon"><Mail size={17}/><input required type="email" autoComplete="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="correo@ejemplo.com"/></div></label><label>Contraseña<div className="input-icon"><LockKeyhole size={17}/><input required type="password" autoComplete="current-password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="••••••••"/></div></label><button className="btn primary full">Entrar</button><div className="auth-footer">¿No tienes cuenta? <Link to="/register">Crear una cuenta ciudadana</Link></div><Link className="back-link" to="/">Volver a la presentación</Link></form></div></div>
}

export function RegisterPage(){
  const { register }=usePulse(); const nav=useNavigate(); const [error,setError]=useState(''); const [form,setForm]=useState({fullName:'',email:'',password:''})
  const submit=async e=>{e.preventDefault();if(form.password.length<6)return setError('Usa al menos 6 caracteres.');const r=await register(form);if(!r.ok)return setError(r.message);nav('/onboarding')}
  return <div className="auth-page"><SimulationBanner/><div className="auth-wrap register-wrap"><div className="auth-info"><Brand light/><span className="eyebrow dark">PULSE CITIZEN</span><h1>Crea tu cuenta</h1><p>Después del registro completarás una ficha personal para que el flujo de emergencia pueda demostrarse de principio a fin.</p><ul className="check-list"><li><ShieldCheck/>Datos personales básicos</li><li><ShieldCheck/>Ficha médica de emergencia</li><li><ShieldCheck/>Contactos y permisos</li></ul></div><form className="auth-card" onSubmit={submit}><div className="auth-icon"><UserRound/></div><h2>Registro ciudadano</h2>{error&&<div className="form-error" role="alert">{error}</div>}<label>Nombre completo<input required autoComplete="name" value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})}/></label><label>Correo<input required type="email" autoComplete="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Contraseña<input required type="password" autoComplete="new-password" minLength="6" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><label className="check-row"><input required type="checkbox"/>Acepto usar únicamente datos ficticios en esta demostración.</label><button className="btn primary full">Crear cuenta</button><div className="auth-footer">¿Ya tienes cuenta? <Link to="/login">Iniciar sesión</Link></div></form></div></div>
}
