import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { HeartPulse, MapPin, UserRound, UsersRound } from 'lucide-react'
import { usePulse } from '../context/PulseContext'
import { SimulationBanner } from '../components/Common'
import { Brand } from '../components/Brand'

export default function OnboardingPage(){
  const {currentUser,updateProfile}=usePulse(); const nav=useNavigate(); const [step,setStep]=useState(1); const [error,setError]=useState('')
  const [form,setForm]=useState({...currentUser?.profile, contacts: currentUser?.profile?.contacts?.length?currentUser.profile.contacts:[{id:`ct-${Date.now()}`,name:'',relation:'',phone:'',email:'',priority:1}]})
  const set=(k,v)=>setForm(f=>({...f,[k]:v})); const consent=(k,v)=>setForm(f=>({...f,consents:{...f.consents,[k]:v}}))
  const next=async e=>{e.preventDefault();if(step<3){setStep(step+1);return}setError('');const result=await updateProfile(form);if(!result?.ok){setError(result?.message||'No se pudo guardar la ficha.');return}nav('/app')}
  return <div className="onboarding"><SimulationBanner/><header><Brand/><span>Paso {step} de 3</span></header><main><div className="onboard-side"><div className="onboard-progress"><i className={step>=1?'done':''}/><i className={step>=2?'done':''}/><i className={step>=3?'done':''}/></div><h1>Prepara tu ficha de emergencia</h1><p>Estos datos se usarán únicamente dentro de la simulación para mostrar qué información puede consultar un operador autorizado.</p><img src="/assets/presentation/profile-preview.jpg" alt="Referencia visual de ficha personal"/></div><form className="onboard-card" onSubmit={next}>{error&&<div className="form-error" role="alert">{error}</div>}{step===1&&<><div className="step-title"><UserRound/><div><span>IDENTIFICACIÓN</span><h2>Datos personales</h2></div></div><div className="form-grid"><label className="span-2">Nombre completo<input required value={form.fullName||''} onChange={e=>set('fullName',e.target.value)}/></label><label>Documento<input required value={form.document||''} onChange={e=>set('document',e.target.value)} placeholder="DEMO-0001"/></label><label>Fecha de nacimiento<input type="date" value={form.birthDate||''} onChange={e=>set('birthDate',e.target.value)}/></label><label>Teléfono<input value={form.phone||''} onChange={e=>set('phone',e.target.value)}/></label><label>Provincia<input value={form.province||''} onChange={e=>set('province',e.target.value)} placeholder="Puntarenas"/></label><label>Cantón<input value={form.canton||''} onChange={e=>set('canton',e.target.value)}/></label><label>Distrito<input value={form.district||''} onChange={e=>set('district',e.target.value)}/></label><label className="span-2">Dirección<input value={form.address||''} onChange={e=>set('address',e.target.value)}/></label></div></>}
  {step===2&&<><div className="step-title"><HeartPulse/><div><span>FICHA DE EMERGENCIA</span><h2>Información médica declarada</h2></div></div><div className="info-note">No se realizan diagnósticos. Esta sección solo almacena información declarada por el usuario.</div><div className="form-grid"><label>Tipo de sangre<select value={form.bloodType||''} onChange={e=>set('bloodType',e.target.value)}><option value="">No indicado</option>{['O+','O-','A+','A-','B+','B-','AB+','AB-'].map(x=><option key={x}>{x}</option>)}</select></label><label>Alergias<input value={form.allergies||''} onChange={e=>set('allergies',e.target.value)}/></label><label>Medicamentos relevantes<input value={form.medications||''} onChange={e=>set('medications',e.target.value)}/></label><label>Condiciones importantes<input value={form.conditions||''} onChange={e=>set('conditions',e.target.value)}/></label><label className="span-2">Movilidad / requerimientos especiales<textarea value={form.mobility||''} onChange={e=>set('mobility',e.target.value)}/></label></div></>}
  {step===3&&<><div className="step-title"><UsersRound/><div><span>CONTACTO Y PRIVACIDAD</span><h2>Contacto principal y permisos</h2></div></div><div className="form-grid"><label>Nombre del contacto<input value={form.contacts[0]?.name||''} onChange={e=>setForm({...form,contacts:[{...form.contacts[0],name:e.target.value}]})}/></label><label>Parentesco<input value={form.contacts[0]?.relation||''} onChange={e=>setForm({...form,contacts:[{...form.contacts[0],relation:e.target.value}]})}/></label><label>Teléfono<input value={form.contacts[0]?.phone||''} onChange={e=>setForm({...form,contacts:[{...form.contacts[0],phone:e.target.value}]})}/></label><label>Email<input value={form.contacts[0]?.email||''} onChange={e=>setForm({...form,contacts:[{...form.contacts[0],email:e.target.value}]})}/></label></div><div className="consents"><label><input type="checkbox" checked={form.consents?.location||false} onChange={e=>consent('location',e.target.checked)}/><MapPin/>Compartir ubicación durante incidentes.</label><label><input type="checkbox" checked={form.consents?.medical||false} onChange={e=>consent('medical',e.target.checked)}/><HeartPulse/>Compartir ficha médica con personal autorizado.</label><label><input type="checkbox" checked={form.consents?.notifyContact||false} onChange={e=>consent('notifyContact',e.target.checked)}/><UsersRound/>Avisar al contacto principal dentro de la simulación.</label></div></>}
  <div className="wizard-actions">{step>1&&<button type="button" className="btn ghost" onClick={()=>setStep(step-1)}>Atrás</button>}<button className="btn primary">{step===3?'Guardar y entrar':'Continuar'}</button></div></form></main></div>
}
