import { useState } from 'react'
import { Camera, CheckCircle2, MapPin, Plus, ShieldAlert, Siren, XCircle } from 'lucide-react'
import { usePulse } from '../../context/PulseContext'
import GeoMap from '../../components/GeoMap'
import { Badge } from '../../components/Common'
import { DEMO_MAP_CENTER } from '../../config/demoGeography'

export function CommunityPage(){
  const {db,addPublication}=usePulse();
  const [form,setForm]=useState({title:'',category:'road_hazard',severity:'medium',description:'',location:{label:'Sector demo',...DEMO_MAP_CENTER},image:''})
  const [open,setOpen]=useState(false)
  const submit=e=>{e.preventDefault();addPublication(form);setOpen(false);setForm(v=>({...v,title:'',description:''}))}
  return <div className="page-stack"><div className="page-heading"><div><span className="eyebrow">RED CÍVICA</span><h1>Publicaciones comunitarias</h1><p>Comparte información sobre lugares peligrosos, accidentes u obstáculos. Command revisa el contenido antes de convertirlo en una alerta operativa.</p></div><button className="btn primary" onClick={()=>setOpen(true)}><Plus size={16}/>Nueva publicación</button></div><div className="community-layout"><section className="panel"><div className="panel-title"><MapPin/><h2>Mapa comunitario</h2></div><GeoMap riskZones={db.riskZones||[]} incidents={db.incidents.filter(i=>i.publicVisibility)} alerts={db.alerts} initialCenter={form.location} initialZoom={14}/></section><aside className="community-list">{(db.publications||[]).map(p=><article className="community-card" key={p.id}><div className="community-card-head"><Badge tone={p.status==='verified'||p.status==='published'?'green':p.status==='rejected'?'red':'amber'}>{p.status}</Badge><span>{new Date(p.createdAt).toLocaleDateString('es-CR')}</span></div><h3>{p.title}</h3><p>{p.description}</p><span><MapPin size={13}/>{p.location?.label}</span></article>)}{!(db.publications||[]).length&&<div className="empty"><ShieldAlert/><h3>Aún no hay publicaciones</h3></div>}</aside></div>{open&&<div className="course-modal-backdrop" onClick={()=>setOpen(false)}><form className="community-modal" onClick={e=>e.stopPropagation()} onSubmit={submit}><button type="button" className="course-modal-close" onClick={()=>setOpen(false)}><XCircle/></button><span className="eyebrow">NUEVO REPORTE COMUNITARIO</span><h2>Comparte una situación</h2><label>Título<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><div className="form-grid"><label>Categoría<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option value="road_hazard">Riesgo vial</option><option value="traffic_accident">Accidente</option><option value="flood">Inundación</option><option value="fire">Incendio</option><option value="other">Otro</option></select></label><label>Severidad<select value={form.severity} onChange={e=>setForm({...form,severity:e.target.value})}><option value="low">Baja</option><option value="medium">Media</option><option value="high">Alta</option></select></label></div><label>Descripción<textarea required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="community-map-picker"><GeoMap compact riskZones={[{id:'draft',...form,title:form.title||'Nuevo punto',radiusM:180}]} selectedId="draft" initialCenter={form.location} initialZoom={15} onMapClick={ll=>setForm({...form,location:{...ll,label:'Punto seleccionado en mapa'}})}/></div><div className="wizard-actions"><button type="button" className="btn ghost" onClick={()=>setOpen(false)}>Cancelar</button><button className="btn primary"><Camera size={15}/>Publicar para revisión</button></div></form></div>}</div>
}

export function NotificationsPage(){
  const {db,markNotificationRead,markAllNotificationsRead}=usePulse(); const notifications=db.notifications||[]
  return <div className="page-stack"><div className="page-heading"><div><span className="eyebrow">CENTRO DE AVISOS</span><h1>Notificaciones</h1><p>Seguimiento de cambios importantes de tus incidentes y de la red cívica.</p></div><button className="btn ghost" onClick={markAllNotificationsRead}>Marcar todo como leído</button></div><div className="notification-page-list">{notifications.map(n=><button key={n.id} className={!n.read?'unread':''} onClick={()=>markNotificationRead(n.id)}><div className="notification-icon"><Siren size={17}/></div><div><strong>{n.title}</strong><p>{n.message}</p><span>{new Date(n.at).toLocaleString('es-CR')}</span></div>{!n.read&&<i/>}</button>)}{!notifications.length&&<div className="empty"><CheckCircle2/><h3>Todo tranquilo</h3><p>No hay notificaciones pendientes.</p></div>}</div></div>
}
