import { Link, useParams, useSearchParams } from 'react-router-dom'
import { Ambulance, ChevronRight, Clock3, HeartHandshake, MessageSquareText, ShieldCheck } from 'lucide-react'
import { usePulse } from '../../context/PulseContext'
import GeoMap from '../../components/GeoMap'
import { EmptyState, IncidentMeta, StatusBadge } from '../../components/Common'
import { incidentImage } from '../../utils/incidentMedia'
import { formatDateTime } from '../../utils/dateTime'

export function MyIncidents(){
 const {db,currentUser}=usePulse();const [params,setParams]=useSearchParams();const q=params.get('q')||'';const mine=db.incidents.filter(i=>i.citizenId===currentUser.id).filter(i=>`${i.code} ${i.title} ${i.location?.label||''}`.toLowerCase().includes(q.toLowerCase()))
 return <div className="page-stack"><div className="page-heading"><div><span className="eyebrow">HISTORIAL PERSONAL</span><h1>Mis incidentes</h1><p>Consulta el estado, recursos y línea de tiempo de tus reportes.</p></div><Link className="btn emergency" to="/app/report">Nuevo reporte</Link></div><div className="incident-search-box"><input value={q} onChange={e=>setParams(e.target.value?{q:e.target.value}:{})} placeholder="Buscar por código, tipo o ubicación..."/><span>{mine.length} resultado(s)</span></div>{!mine.length?<EmptyState title="No hay reportes que coincidan" text="Prueba con otro código, tipo o ubicación."/>:<div className="incident-list">{mine.map(i=><Link key={i.id} to={`/app/incidents/${i.id}`} className="incident-card"><img className="incident-list-thumb" src={incidentImage(i)} alt=""/><div className="priority-box">{i.priority}</div><div className="grow"><div className="incident-card-top"><span>{i.code}</span><StatusBadge status={i.status}/></div><h3>{i.title}</h3><p>{i.description}</p><IncidentMeta incident={i}/></div><ChevronRight/></Link>)}</div>}</div>
}

export function IncidentDetail(){
 const {id}=useParams();const {db,currentUser}=usePulse();const incident=db.incidents.find(i=>i.id===id&&i.citizenId===currentUser.id);if(!incident)return <EmptyState title="Incidente no encontrado" text="No tienes acceso a este caso."/>
 const units=db.units.filter(u=>[...new Set([...(incident.assignedUnits||[]),incident.assignedUnit].filter(Boolean))].includes(u.id));const activeUnit=units.find(u=>['en_route','on_scene','transporting'].includes(u.status))||units[0];const resolved=['resolved','at_hospital'].includes(incident.status)
 const recovery=(db.resources||[]).filter(r=>r.kind==='physical'||r.kind==='wellbeing').slice(0,3)
 return <div className="page-stack"><div className="incident-detail-head"><div><span className="eyebrow">SEGUIMIENTO DE EMERGENCIA</span><h1>{incident.code}</h1><p>{incident.title}</p></div><div className="detail-status"><span>{incident.priority} · Riesgo {incident.riskScore}/100</span><StatusBadge status={incident.status}/></div></div><div className="detail-grid"><section className="panel"><h2>Situación</h2><div className="citizen-incident-media"><img src={incidentImage(incident)} alt={`Imagen asociada a ${incident.title}`}/><span>{incident.image?.startsWith('data:')?'Fotografía adjunta al reporte':'Imagen representativa de la categoría'}</span></div><p>{incident.description}</p><IncidentMeta incident={incident}/><div className="detail-data">{Object.entries(incident.details||{}).map(([k,v])=><div key={k}><span>{k.replace(/([A-Z])/g,' $1')}</span><strong>{String(v)}</strong></div>)}</div></section><section className="panel unit-panel"><h2>Respuesta asignada</h2>{activeUnit?<><div className="unit-feature"><Ambulance/><div><strong>{activeUnit.id}</strong><span>{activeUnit.type} · {activeUnit.status.replaceAll('_',' ')} · {activeUnit.status==='en_route'?`${Math.max(0,Math.ceil((1-(activeUnit.mission?.progress||0))*(activeUnit.mission?.etaMin||activeUnit.eta)))} min restantes`:'Seguimiento activo'}</span></div></div><GeoMap compact incidents={[incident]} units={units} hospitals={db.hospitals||[]} selectedId={incident.id} focusLocations={[incident.location,...units.map(u=>u.location).filter(Boolean)]} focusKey={`detail-${incident.id}`} initialCenter={incident.location} initialZoom={15}/></>:<div className="pending-box"><Clock3/>Aún no se ha asignado una unidad.</div>}</section></div><section className="panel"><div className="panel-title"><MessageSquareText/><h3>Línea de tiempo</h3></div><div className="timeline">{(incident.timeline||[]).map((t,idx)=><div key={t.id} className="timeline-item"><i className={idx===incident.timeline.length-1?'current':''}/><div><strong>{t.label}</strong><span>{formatDateTime(t.at)}</span></div></div>)}</div></section>{resolved&&<section className="post-emergency-panel"><div className="post-emergency-head"><div><HeartHandshake/><div><span>POST-EMERGENCIA</span><h2>El caso ya tiene una siguiente etapa</h2></div></div><ShieldCheck/></div><p>Consulta recursos educativos relacionados con recuperación, documentación y bienestar después del evento.</p><div className="recovery-resource-grid">{recovery.map(r=><Link key={r.id} to="/app/resources"><img src={r.image} alt=""/><div><strong>{r.title}</strong><span>{r.duration} · {r.level}</span></div></Link>)}</div></section>}</div>
}
