import { useEffect, useMemo, useRef, useState } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { AlertOctagon, Ambulance, Camera, Car, CloudRain, Flame, ImagePlus, MapPin, ShieldAlert, Siren, TreePine, UploadCloud, UserRoundSearch, Waves, X } from 'lucide-react'
import { usePulse } from '../../context/PulseContext'
import { useLiveLocation } from '../../context/LiveLocationContext'
import GeoMap from '../../components/GeoMap'
import { InlineNotice } from '../../components/Common'
import { DEMO_MAP_CENTER } from '../../config/demoGeography'
import { INCIDENT_MEDIA } from '../../utils/incidentMedia'
import { calculateRiskScore, findDuplicateCandidates } from '../../utils/incidentEngine'

const categories=[['medical','Médica',Ambulance,'P1'],['traffic_accident','Accidente vehicular',Car,'P1'],['fire','Incendio',Flame,'P1'],['security','Seguridad',ShieldAlert,'P1'],['flood','Inundación',Waves,'P2'],['landslide','Deslizamiento',TreePine,'P2'],['missing_person','Persona desaparecida',UserRoundSearch,'P2'],['weather','Evento climático',CloudRain,'P2'],['road_hazard','Riesgo vial',AlertOctagon,'P3'],['other','Otra emergencia',Siren,'P2']]
const fieldMap={
  traffic_accident:[['vehicles','Cantidad de vehículos','number'],['people','Personas aproximadas','number'],['injured','¿Hay heridos?','select'],['injuredCount','¿Cuántas personas heridas?','number'],['trapped','¿Hay personas atrapadas?','select'],['fire','¿Hay fuego o humo?','select'],['roadBlocked','¿La vía está bloqueada?','select'],['fuelLeak','¿Hay derrame de combustible?','select']],
  fire:[['structure','Tipo de estructura','text'],['peopleInside','¿Hay personas dentro?','select'],['smoke','¿Hay humo?','select'],['propagation','¿Se está propagando?','select'],['gas','¿Hay cilindros o gas?','select']],
  medical:[['conscious','¿La persona está consciente?','select'],['breathing','¿Respira?','select'],['age','Edad aproximada','number'],['bleeding','¿Hay sangrado visible?','select'],['canSpeak','¿Puede hablar?','select']],
  flood:[['waterHeight','Altura aproximada del agua (cm)','number'],['homes','Viviendas afectadas','number'],['trapped','¿Personas atrapadas?','select'],['strongCurrent','¿Corriente fuerte?','select']]
}
function compressImage(file){return new Promise((resolve,reject)=>{if(!file?.type?.startsWith('image/'))return reject(new Error('Selecciona una imagen válida.'));if(file.size>8*1024*1024)return reject(new Error('La imagen supera 8 MB.'));const reader=new FileReader();reader.onload=()=>{const image=new Image();image.onload=()=>{const max=1280,scale=Math.min(1,max/Math.max(image.width,image.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',0.76))};image.onerror=()=>reject(new Error('No se pudo procesar la imagen.'));image.src=reader.result};reader.onerror=()=>reject(new Error('No se pudo leer el archivo.'));reader.readAsDataURL(file)})}

export default function ReportEmergency(){
  const {addIncident,db}=usePulse(); const nav=useNavigate(); const [params]=useSearchParams(); const isSos=params.get('sos')==='1'; const [step,setStep]=useState(isSos?0:1); const [hold,setHold]=useState(false); const [geoNotice,setGeoNotice]=useState(null); const holdTimer=useRef(null); const [mediaError,setMediaError]=useState(''); const fileRef=useRef(null)
  const {location:liveLocation,status:liveLocationStatus,error:liveLocationError,start:startLiveLocation}=useLiveLocation(); const [followLiveLocation,setFollowLiveLocation]=useState(false)
  const [form,setForm]=useState({category:'',title:'',priority:'P2',description:'',canTalk:true,publicVisibility:false,location:{label:'El Roble, Puntarenas (demo)',...DEMO_MAP_CENTER},details:{},imageData:'',imageName:''})
  const cat=useMemo(()=>categories.find(c=>c[0]===form.category),[form.category]); const fields=fieldMap[form.category]||[['people','Personas afectadas (aprox.)','number'],['risk','Riesgo principal observado','text']]
  const draftIncident=useMemo(()=>({...form,createdAt:new Date().toISOString(),citizenId:'draft'}),[form]); const risk=useMemo(()=>calculateRiskScore(draftIncident,db.riskZones||[]),[draftIncident,db.riskZones]); const duplicates=useMemo(()=>findDuplicateCandidates(draftIncident,db.incidents||[]),[draftIncident,db.incidents])
  const selectCat=c=>{setForm({...form,category:c[0],title:c[1],priority:c[3],details:{},imageData:'',imageName:''});setStep(2)}
  const send=e=>{e.preventDefault();const inc=addIncident({...form,priority:risk.priority});if(inc)nav(`/app/incidents/${inc.id}`)}
  const geolocate=()=>{if(followLiveLocation){setFollowLiveLocation(false);setGeoNotice({tone:'info',text:'Seguimiento pausado para este reporte. Puedes ajustar el punto manualmente.'});return} setFollowLiveLocation(true);startLiveLocation();setGeoNotice({tone:'info',text:'Solicitando permiso y buscando tu ubicación…'})}
  const chooseImage=async file=>{if(!file)return;setMediaError('');try{const data=await compressImage(file);setForm(v=>({...v,imageData:data,imageName:file.name}))}catch(err){setMediaError(err.message)}}
  const fallback=INCIDENT_MEDIA[form.category]||INCIDENT_MEDIA.other
  useEffect(()=>{if(!followLiveLocation||!liveLocation)return;setForm(v=>({...v,location:{...v.location,label:'Ubicación actual del dispositivo',lat:liveLocation.lat,lng:liveLocation.lng,accuracy:liveLocation.accuracy}}));setGeoNotice({tone:'success',text:`Ubicación en vivo aplicada · precisión aproximada ${Math.round(liveLocation.accuracy||0)} m.`})},[followLiveLocation,liveLocation])
  useEffect(()=>{if(followLiveLocation&&liveLocationError)setGeoNotice({tone:'error',text:liveLocationError})},[followLiveLocation,liveLocationError])
  const startHold=()=>{setHold(true);holdTimer.current=setTimeout(()=>setStep(1),3000)}; const endHold=()=>{setHold(false);if(holdTimer.current)clearTimeout(holdTimer.current)}
  if(step===0)return <div className="sos-screen"><span className="eyebrow">ACTIVACIÓN REFORZADA</span><h1>Modo SOS</h1><p>Para evitar activaciones accidentales, mantén presionado el botón durante 3 segundos. Esta acción solo crea un incidente dentro de la demo.</p><button className="sos-hold" onMouseDown={startHold} onMouseUp={endHold} onMouseLeave={endHold} onTouchStart={startHold} onTouchEnd={endHold}><span className={hold?'holding':''}>SOS</span><small>MANTENER 3 SEGUNDOS</small></button><button className="btn ghost" onClick={()=>setStep(1)}>Usar alternativa accesible con confirmación</button></div>
  return <div className="report-page"><div className="page-heading"><div><span className="eyebrow">NUEVO REPORTE</span><h1>Reportar una emergencia</h1><p>El asistente adapta las preguntas al tipo de emergencia y calcula una prioridad demostrativa antes de enviar.</p></div><div className="step-pills"><span className={step>=1?'active':''}>1 Tipo</span><span className={step>=2?'active':''}>2 Detalles</span><span className={step>=3?'active':''}>3 Ubicación</span><span className={step>=4?'active':''}>4 Evidencia</span><span className={step>=5?'active':''}>5 Confirmar</span></div></div>
    {step===1&&<div className="catalog-grid">{categories.map(c=>{const Icon=c[2];return <button key={c[0]} onClick={()=>selectCat(c)}><span className="catalog-icon"><Icon/></span><strong>{c[1]}</strong><span>Formulario guiado · prioridad inicial {c[3]}</span></button>})}</div>}
    {step===2&&<form className="report-card" onSubmit={e=>{e.preventDefault();setStep(3)}}><div className="report-title"><span className="catalog-icon">{cat&&(()=>{const I=cat[2];return <I/>})()}</span><div><span>{cat?.[1]}</span><h2>¿Qué está ocurriendo?</h2></div></div><label>Descripción breve<textarea required rows="4" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Describe lo que ves sin asumir diagnósticos..."/></label><div className="form-grid">{fields.map(([key,label,type])=><label key={key}>{label}{type==='select'?<select value={form.details[key]||''} onChange={e=>setForm({...form,details:{...form.details,[key]:e.target.value}})}><option value="">Desconocido</option><option>Sí</option><option>No</option><option>Parcial</option></select>:<input type={type} value={form.details[key]||''} onChange={e=>setForm({...form,details:{...form.details,[key]:e.target.value}})}/>}</label>)}</div><fieldset><legend>¿Puedes hablar de forma segura?</legend><div className="choice-row">{[['Sí',true],['No',false]].map(([l,v])=><button type="button" key={l} className={form.canTalk===v?'selected':''} onClick={()=>setForm({...form,canTalk:v})}>{l}</button>)}</div></fieldset><div className="risk-preview"><div><span>Prioridad estimada</span><strong>{risk.priority} · {risk.score}/100</strong></div><div>{risk.reasons.slice(0,3).map(r=><span key={r}>+ {r}</span>)}</div></div><div className="wizard-actions"><button type="button" className="btn ghost" onClick={()=>setStep(1)}>Atrás</button><button className="btn primary">Continuar</button></div></form>}
    {step===3&&<div className="report-card"><div className="report-title"><span className="catalog-icon"><MapPin/></span><div><span>UBICACIÓN</span><h2>¿Dónde ocurrió?</h2></div></div><div className="location-grid"><div><label>Dirección o referencia<input value={form.location.label} onChange={e=>setForm({...form,location:{...form.location,label:e.target.value}})}/></label><button className={`btn secondary live-report-location ${followLiveLocation?'active':''}`} type="button" onClick={geolocate}><MapPin size={17}/>{followLiveLocation?'Dejar de seguir ubicación':liveLocationStatus==='requesting'?'Buscando ubicación…':'Usar mi ubicación en vivo'}</button>{geoNotice&&<InlineNotice tone={geoNotice.tone}>{geoNotice.text}</InlineNotice>}<p className="help">Puedes seguir tu posición en tiempo real o hacer clic en el mapa para fijar el punto manualmente. La ubicación permanece en esta demostración local.</p></div><GeoMap compact incidents={[{id:'preview',category:form.category,location:form.location,code:'Vista previa',title:form.title,priority:risk.priority,status:'received'}]} userLocation={liveLocation} focusLocations={followLiveLocation&&liveLocation?[liveLocation]:[]} focusKey={followLiveLocation&&liveLocation?'report-live-ready':''} initialCenter={form.location} initialZoom={15} onMapClick={ll=>{setFollowLiveLocation(false);setForm({...form,location:{...form.location,...ll,label:'Punto seleccionado en mapa (demo)'}})}}/></div><div className="wizard-actions"><button className="btn ghost" onClick={()=>setStep(2)}>Atrás</button><button className="btn primary" onClick={()=>setStep(4)}>Continuar</button></div></div>}
    {step===4&&<div className="report-card evidence-card"><div className="report-title"><span className="catalog-icon"><Camera/></span><div><span>EVIDENCIA VISUAL</span><h2>Agrega una foto si es seguro hacerlo</h2></div></div><p className="help">No te acerques al peligro para tomar una imagen.</p><div className="evidence-layout"><button type="button" className="evidence-drop" onClick={()=>fileRef.current?.click()}><UploadCloud size={30}/><strong>Seleccionar fotografía</strong><span>JPG, PNG o WEBP · máximo 8 MB</span></button><input ref={fileRef} type="file" accept="image/*" hidden onChange={e=>chooseImage(e.target.files?.[0])}/><div className="evidence-preview"><img src={form.imageData||fallback} alt="Vista previa del incidente"/>{form.imageData?<><button type="button" onClick={()=>setForm({...form,imageData:'',imageName:''})}><X size={16}/></button><span><ImagePlus size={14}/>{form.imageName}</span></>:<span>Imagen representativa de respaldo</span>}</div></div>{mediaError&&<div className="form-error">{mediaError}</div>}<label className="check-row"><input type="checkbox" checked={form.publicVisibility} onChange={e=>setForm({...form,publicVisibility:e.target.checked})}/>Permitir que el caso se muestre anonimizado en el feed comunitario.</label><div className="wizard-actions"><button className="btn ghost" onClick={()=>setStep(3)}>Atrás</button><button className="btn primary" onClick={()=>setStep(5)}>Revisar reporte</button></div></div>}
    {step===5&&<form className="report-card" onSubmit={send}><div className="confirm-emergency"><Siren/><div><span>LISTO PARA ENVIAR</span><h2>{form.title}</h2><p>{form.description}</p></div></div><div className="confirm-media"><img src={form.imageData||fallback} alt="Evidencia o imagen representativa"/><div><strong>{form.imageData?'Fotografía adjunta':'Imagen representativa de la categoría'}</strong><span>{form.location.label}</span><small>{form.publicVisibility?'Se mostrará de forma anonimizada en el feed comunitario.':'Solo será visible dentro del flujo del caso.'}</small></div></div><div className="summary-grid"><div><span>Prioridad calculada</span><strong>{risk.priority} · {risk.score}/100</strong></div><div><span>Ubicación</span><strong>{form.location.label}</strong></div><div><span>Comunicación</span><strong>{form.canTalk?'Puede hablar':'Modo sin voz'}</strong></div></div>{duplicates.length>0&&<div className="duplicate-warning"><FlagIcon/><div><strong>Hay {duplicates.length} posible(s) reporte(s) coincidente(s)</strong><span>{duplicates.map(d=>d.code).join(' · ')}</span></div></div>}<div className="simulation-confirm">Al confirmar, el reporte aparecerá en PULSE Command dentro de este navegador. No se enviará a autoridades reales.</div><div className="wizard-actions"><button type="button" className="btn ghost" onClick={()=>setStep(4)}>Atrás</button><button className="btn emergency"><Siren size={18}/>Enviar reporte demo</button></div></form>}
  </div>
}
function FlagIcon(){return <ShieldAlert size={18}/>} 
