import { useMemo, useState } from 'react'
import { Ambulance, BellRing, ChevronRight, FileHeart, Flag, MapPin, MessageSquareText, Navigation, ShieldAlert, ShieldCheck, UserRound } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { usePulse } from '../../context/PulseContext'
import GeoMap from '../../components/GeoMap'
import { Badge, InlineNotice, StatusBadge } from '../../components/Common'
import { incidentImage } from '../../utils/incidentMedia'
import { compatibleUnits, requiredCapabilities } from '../../utils/dispatch'

const detailLabels={vehicles:'Vehículos involucrados',people:'Personas afectadas',injured:'Personas heridas',injuredCount:'Heridos contados',trapped:'Personas atrapadas',fire:'Fuego',smoke:'Humo',fuelLeak:'Derrame de combustible',roadBlocked:'Estado de la vía',heavyVehicle:'Vehículo pesado',weather:'Condiciones climáticas',structure:'Tipo de estructura',peopleInside:'Personas dentro',propagation:'Propagación',gas:'Gas / cilindros',hazmat:'Material peligroso',floors:'Pisos',conscious:'Consciente',breathing:'Respira',age:'Edad aproximada',bleeding:'Sangrado',canSpeak:'Puede hablar',waterHeight:'Nivel de agua',homes:'Viviendas afectadas',strongCurrent:'Corriente fuerte',hazard:'Peligro observado',visibility:'Visibilidad'}

export function AdminIncidents(){
  const {db}=usePulse(); const [q,setQ]=useState(''); const [status,setStatus]=useState('all')
  const list=useMemo(()=>db.incidents.filter(i=>`${i.code} ${i.title} ${i.location?.label||''}`.toLowerCase().includes(q.toLowerCase())).filter(i=>status==='all'||i.status===status),[db.incidents,q,status])
  return <div className="admin-page"><div className="admin-toolbar admin-toolbar-compact"><div className="incident-toolbar-actions"><input aria-label="Buscar incidentes" placeholder="Buscar por código, tipo o ubicación..." value={q} onChange={e=>setQ(e.target.value)}/><select aria-label="Filtrar incidentes por estado" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Todos los estados</option><option value="received">Recibidos</option><option value="validated">Validados</option><option value="en_route">En ruta</option><option value="on_scene">En sitio</option><option value="transporting">Trasladando</option><option value="at_hospital">En hospital</option><option value="resolved">Resueltos</option></select></div></div><div className="admin-table"><div className="admin-table-head"><span>Prioridad</span><span>Código / Tipo</span><span>Ubicación</span><span>Estado</span><span>Recursos</span><span/></div>{list.map(i=>{const assigned=[...new Set([...(i.assignedUnits||[]),i.assignedUnit].filter(Boolean))];return <Link key={i.id} to={`/command/incidents/${i.id}`} className="admin-table-row"><span><b className={`priority-chip ${i.priority.toLowerCase()}`}>{i.priority}</b></span><span><strong>{i.code}</strong><small>{i.title}</small></span><span>{i.location?.label}</span><span><StatusBadge status={i.status}/></span><span>{assigned.length?`${assigned.length} asignada(s)`:'Sin asignar'}</span><ChevronRight/></Link>})}</div></div>
}

export function AdminIncidentDetail(){
  const {id}=useParams();
  const {db,updateIncident,dispatchUnit,startTransport,closeIncident,createAlertFromIncident,mergeReports}=usePulse()
  const incident=db.incidents.find(i=>i.id===id)
  const [tab,setTab]=useState('summary')
  const [hospitalId,setHospitalId]=useState('')
  const [resolution,setResolution]=useState('Atención completada dentro del escenario de demostración.')
  const [actionNotice,setActionNotice]=useState(null)
  if(!incident)return <div className="admin-page"><div className="empty"><ShieldCheck size={32}/><h3>Incidente no encontrado</h3><p>El expediente no existe o fue restablecido.</p></div></div>
  const citizen=db.users.find(u=>u.id===incident.citizenId); const profile=citizen?.profile
  const recommended=compatibleUnits(incident,db.units); const needs=requiredCapabilities(incident.category)
  const assignedIds=[...new Set([...(incident.assignedUnits||[]),incident.assignedUnit].filter(Boolean))]; const assigned=db.units.filter(u=>assignedIds.includes(u.id))
  const availableHospitals=(db.hospitals||[]).filter(h=>h.status!=='full'&&h.receivesTransfers!==false)
  const duplicateCandidates=(incident.duplicateCandidates||[]).map(cid=>db.incidents.find(i=>i.id===cid)).filter(Boolean)
  const status=(s,label)=>{updateIncident(id,{status:s},label);setActionNotice({tone:'success',text:label})}
  const firstUnit=assigned.find(u=>u.status==='on_scene')
  const transport=()=>{if(!firstUnit||!hospitalId){setActionNotice({tone:'error',text:'Selecciona un hospital y espera a que una unidad esté en sitio.'});return}const result=startTransport(id,firstUnit.id,hospitalId);setActionNotice(result.ok?{tone:'success',text:'Traslado hospitalario iniciado.'}:{tone:'error',text:result.message})}
  const doDispatch=u=>{const result=dispatchUnit(id,u.id);setActionNotice(result.ok?{tone:'success',text:`${u.id} despachada correctamente.`}:{tone:'error',text:result.message})}
  const publishAlert=()=>{createAlertFromIncident(id);setActionNotice({tone:'success',text:'Alerta geográfica creada a partir del incidente.'})}
  const finishIncident=()=>{closeIncident(id,{summary:resolution,closedBy:'Operador Demo'});setActionNotice({tone:'success',text:'Incidente cerrado. Las unidades asignadas iniciaron retorno a base.'})}
  return <div className="admin-page incident-detail-v5">
    <div className="incident-admin-head"><div><span className="eyebrow dark">EXPEDIENTE OPERATIVO</span><h2>{incident.code}</h2><p>{incident.title} · {incident.location?.label}</p></div><div className="admin-status-pair"><b className={`priority-chip ${incident.priority.toLowerCase()}`}>{incident.priority}</b><StatusBadge status={incident.status}/></div></div>

    {actionNotice&&<InlineNotice tone={actionNotice.tone}>{actionNotice.text}</InlineNotice>}
    <div className="incident-tabs"><button className={tab==='summary'?'active':''} onClick={()=>setTab('summary')}>Resumen</button><button className={tab==='resources'?'active':''} onClick={()=>setTab('resources')}>Recursos</button><button className={tab==='communications'?'active':''} onClick={()=>setTab('communications')}>Comunicaciones</button><button className={tab==='evidence'?'active':''} onClick={()=>setTab('evidence')}>Evidencia</button><button className={tab==='timeline'?'active':''} onClick={()=>setTab('timeline')}>Timeline</button><button className={tab==='closure'?'active':''} onClick={()=>setTab('closure')}>Cierre</button></div>

    {tab==='summary'&&<div className="incident-command-grid-v4"><section className="admin-panel case-panel-v4"><div className="panel-title"><MapPin/><h3>Situación y evaluación</h3><Badge tone="red">Riesgo {incident.riskScore||'—'}/100</Badge></div><div className="risk-reasons-detail">{(incident.riskReasons||[]).map(reason=><span key={reason}>{reason}</span>)}</div><p className="case-description">{incident.description}</p><div className="case-detail-grid-v4">{Object.entries(incident.details||{}).map(([k,v])=><div key={k}><span>{detailLabels[k]||k.replace(/([A-Z])/g,' $1')}</span><strong>{String(v)}</strong></div>)}</div>{duplicateCandidates.length>0&&<div className="duplicate-warning"><Flag/><div><strong>Posibles reportes duplicados</strong><span>{duplicateCandidates.map(d=>d.code).join(' · ')}</span></div>{duplicateCandidates.map(d=><button className="btn ghost small" key={d.id} onClick={()=>mergeReports(id,d.id)}>Fusionar {d.code}</button>)}</div>}</section><section className="admin-panel map-case-v4"><div className="panel-title"><Navigation/><h3>Ubicación operativa</h3><Badge tone="blue">{incident.location?.lat?.toFixed?.(4)}, {incident.location?.lng?.toFixed?.(4)}</Badge></div><GeoMap compact incidents={[incident]} units={assigned} riskZones={db.riskZones||[]} alerts={db.alerts||[]} hospitals={db.hospitals||[]} selectedId={incident.id} initialCenter={incident.location} initialZoom={15}/><div className="location-detail-v4"><span>Dirección / zona</span><strong>{incident.location?.label}</strong><span>Referencia</span><strong>{incident.location?.reference||'No indicada'}</strong></div></section><section className="admin-panel citizen-record"><div className="panel-title"><UserRound/><h3>Persona reportante</h3></div>{profile?<><div className="person-card"><div className="avatar">{profile.fullName?.slice(0,2).toUpperCase()}</div><div><strong>{profile.fullName}</strong><span>{citizen.email}</span><small>{profile.document}</small></div></div><div className="personal-grid"><div><span>Teléfono</span><strong>{profile.phone||'No indicado'}</strong></div><div><span>Distrito</span><strong>{profile.district||'No indicado'}</strong></div><div><span>Puede hablar</span><strong>{incident.canTalk?'Sí':'No / limitado'}</strong></div></div>{profile.consents?.medical?<div className="medical-card"><FileHeart/><div><strong>Ficha médica autorizada</strong><span>Sangre {profile.bloodType||'—'} · Alergias: {profile.allergies||'No declaradas'}</span><small>{profile.conditions||'Sin condiciones relevantes declaradas'}</small></div></div>:<div className="access-denied"><ShieldCheck/>El ciudadano no autorizó acceso a la ficha médica.</div>}</>:<div className="access-denied">Reportante demo sin cuenta asociada.</div>}</section></div>}

    {tab==='resources'&&<div className="incident-workflow-grid"><section className="admin-panel"><div className="panel-title"><Ambulance/><h3>Recursos recomendados</h3></div><div className="dispatch-need"><span>Capacidades:</span>{needs.map(n=><b key={n}>{n}</b>)}</div><div className="recommend-list">{recommended.map((u,index)=><div key={u.id} className={index===0?'recommended-unit':''}><div><strong>{u.id} {index===0?<em>RECOMENDADA</em>:null}</strong><span>{u.type} · {u.distanceKm} km · ETA {u.eta} min</span><small>Compatibilidad: {u.compatibility.join(', ')}</small></div><button className="btn primary small" onClick={()=>doDispatch(u)}>Despachar</button></div>)}</div>{assigned.length>0&&<div className="assigned-list-v4"><h4>Unidades asignadas</h4>{assigned.map(u=><div key={u.id}><div><strong>{u.id}</strong><span>{u.type} · {u.status.replaceAll('_',' ')}</span></div><b>{u.status==='en_route'?`${Math.max(0,Math.ceil((1-(u.mission?.progress||0))*(u.mission?.etaMin||u.eta)))} min`:u.status==='transporting'?`${Math.max(0,Math.ceil((1-(u.mission?.progress||0))*(u.mission?.etaMin||u.eta)))} min`:u.status==='at_hospital'?'Hospital':'En sitio'}</b></div>)}</div>}</section><section className="admin-panel"><div className="panel-title"><Building2Icon/><h3>Traslado hospitalario</h3></div><p className="help">Disponible cuando una unidad ya está en sitio. Selecciona un destino con capacidad.</p><select value={hospitalId} onChange={e=>setHospitalId(e.target.value)}><option value="">Seleccionar hospital</option>{availableHospitals.map(h=><option key={h.id} value={h.id}>{h.name} · {h.capacity} cupos</option>)}</select><button className="btn primary full" disabled={!firstUnit||!hospitalId||incident.status==='transporting'} onClick={transport}>Iniciar traslado</button>{incident.hospitalDestination&&<div className="hospital-destination"><strong>{incident.hospitalDestination.name}</strong><span>{incident.status==='at_hospital'?'Paciente recibido':'Destino asignado'}</span></div>}</section></div>}

    {tab==='communications'&&<section className="admin-panel communications-panel"><div className="panel-title"><MessageSquareText/><h3>Comunicaciones del incidente</h3></div><div className="communication-list">{(incident.communications||[]).map(m=><div key={m.id}><b>{m.sender}</b><p>{m.text}</p><span>{new Date(m.at).toLocaleString('es-CR')}</span></div>)}{!(incident.communications||[]).length&&<div className="empty-mini">No hay comunicaciones registradas todavía.</div>}</div><button className="btn ghost" onClick={()=>updateIncident(id,{communications:[...(incident.communications||[]),{id:`msg-${Date.now()}`,sender:'Operador Demo',text:'Se confirma seguimiento del caso y coordinación de recursos.',at:new Date().toISOString()}]},'Comunicación operacional registrada')}>Registrar actualización operacional</button></section>}

    {tab==='evidence'&&<section className="admin-panel evidence-admin-panel"><div className="panel-title"><Flag/><h3>Evidencia</h3><Badge tone="blue">{incident.photos?.length||1} archivo(s)</Badge></div><div className="evidence-admin-grid"><img src={incidentImage(incident)} alt={`Evidencia de ${incident.title}`}/><div><strong>{incident.image?.startsWith('data:')?'Fotografía aportada por ciudadano':'Imagen representativa de la categoría'}</strong><span>La evidencia de esta demo es ficticia o aportada localmente por el usuario.</span><small>Ubicación: {incident.location?.label}</small></div></div></section>}

    {tab==='timeline'&&<section className="admin-panel"><div className="panel-title"><Navigation/><h3>Línea de tiempo operacional</h3></div><div className="timeline dark-timeline">{(incident.timeline||[]).map(t=><div key={t.id} className="timeline-item"><i/><div><strong>{t.label}</strong><span>{new Date(t.at).toLocaleString('es-CR')}</span></div></div>)}</div></section>}

    {tab==='closure'&&<section className="admin-panel closure-panel"><div className="panel-title"><ShieldCheck/><h3>Cierre del incidente</h3></div><div className="closure-summary"><div><span>Estado actual</span><StatusBadge status={incident.status}/></div><div><span>Unidades asignadas</span><strong>{assigned.length}</strong></div><div><span>Destino</span><strong>{incident.hospitalDestination?.name||'Sin hospital'}</strong></div></div><label>Resultado / notas de cierre<textarea rows="5" value={resolution} onChange={e=>setResolution(e.target.value)}/></label><div className="closure-actions"><button className="btn ghost" onClick={()=>status('validated','Caso validado por operador')}>Validar caso</button><button className="btn ghost" onClick={publishAlert}><BellRing size={15}/>Crear alerta geográfica</button><button className="btn emergency" onClick={finishIncident}>Cerrar incidente</button></div><p className="simulation-confirm">Todo el cierre es local y simulado. No se envía información a autoridades reales.</p></section>}
  </div>
}

function Building2Icon(){return <ShieldAlert size={18}/>} 
