import { useState } from 'react'
import { Activity, Ambulance, Building2, CheckCircle2, ClipboardCheck, FileText, MapPin, Play, Radio, ShieldAlert, Siren, Truck, XCircle } from 'lucide-react'
import { usePulse } from '../../context/PulseContext'
import { Badge, StatCard } from '../../components/Common'
import GeoMap from '../../components/GeoMap'
import { UnitTypeIcon } from '../../components/UnitTypeIcon'

const capabilityNames={medical:'Atención médica',traffic_accident:'Accidente vial',fire:'Incendios',rescue:'Rescate',security:'Seguridad',road_hazard:'Riesgo vial',flood:'Inundaciones',missing_person:'Persona desaparecida'}
const unitStatusNames={available:'Disponible',en_route:'En ruta',on_scene:'En sitio',transporting:'Trasladando',at_hospital:'En hospital',returning:'Regresando',out_of_service:'Fuera de servicio'}

export function UnitsPage(){
  const {db, returnUnit}=usePulse(); const [filter,setFilter]=useState('all')
  const units=db.units.filter(u=>filter==='all'||u.status===filter)
  const hospitalNames=Object.fromEntries((db.hospitals||[]).map(h=>[h.id,h.shortName||h.name]))
  return <div className="admin-page"><div className="admin-toolbar admin-toolbar-compact"><select aria-label="Filtrar unidades por estado" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todas las unidades</option><option value="available">Disponibles</option><option value="en_route">En ruta</option><option value="on_scene">En sitio</option><option value="transporting">Trasladando</option><option value="returning">Regresando</option></select></div><div className="admin-stats"><StatCard label="Disponibles" value={db.units.filter(u=>u.status==='available').length} icon={Ambulance} tone="green"/><StatCard label="En ruta" value={db.units.filter(u=>u.status==='en_route').length} icon={Radio} tone="amber"/><StatCard label="En sitio" value={db.units.filter(u=>u.status==='on_scene').length} icon={ShieldAlert}/><StatCard label="Trasladando" value={db.units.filter(u=>u.status==='transporting').length} icon={Truck} tone="red"/></div><section className="admin-panel"><div className="unit-management-grid">{units.map(u=><article className={`resource-unit-card resource-unit-${u.serviceKey||'support'}`} key={u.id}><div className="resource-unit-head"><UnitTypeIcon unit={u}/><div><strong>{u.id}</strong><span>{u.type}</span></div><Badge tone={u.status==='available'?'green':u.status==='en_route'||u.status==='transporting'?'amber':'blue'}>{unitStatusNames[u.status]||u.status}</Badge></div><dl><div><dt>Base / incidente</dt><dd>{u.assignedIncident||hospitalNames[u.baseHospitalId]||'Base operativa'}</dd></div><div><dt>Tripulación</dt><dd>{u.crew||'—'}</dd></div><div className="resource-capabilities"><dt>Capacidades</dt><dd>{(u.capabilities||[]).map(value=>capabilityNames[value]||value).join(' · ')}</dd></div></dl>{u.status==='at_hospital'&&<button className="btn ghost small" onClick={()=>returnUnit(u.id)}>Regresar a {hospitalNames[u.baseHospitalId]||'base'}</button>}{u.status==='on_scene'&&<span className="resource-note">Lista para traslado desde el sitio.</span>}</article>)}</div></section></div>
}

export function HospitalsPage(){
  const {db}=usePulse(); const hospitals=db.hospitals||[]
  const [selectedId,setSelectedId]=useState(null)
  const medicalUnits=db.units.filter(unit=>(unit.capabilities||[]).includes('medical'))
  const selected=hospitals.find(h=>h.id===selectedId)||hospitals[0]
  const unitsAtBase=hospitalId=>medicalUnits.filter(unit=>unit.baseHospitalId===hospitalId)
  return <div className="admin-page hospitals-page-v6"><div className="hospital-network-summary"><div><Building2/><span><strong>{hospitals.length}</strong> centros reales de la zona</span></div><div><Ambulance/><span><strong>{medicalUnits.length}</strong> unidades con base médica</span></div><small>Ubicaciones reales · capacidad y estados simulados</small></div><div className="hospital-network-layout"><section className="admin-panel hospital-network-map"><div className="hospital-map-head"><div><span>RED MÉDICA LOCAL</span><strong>{selectedId?(selected?.shortName||selected?.name):'Cobertura de Puntarenas y Barranca'}</strong><small>{selectedId?selected?.address:'Selecciona un centro para acercar el mapa'}</small></div><Badge tone={selectedId&&selected?.receivesTransfers?'green':'blue'}>{selectedId?(selected?.receivesTransfers?'Recibe traslados':'Base local'):'5 centros'}</Badge></div><GeoMap hospitals={hospitals} units={medicalUnits} selectedId={selectedId} onSelectHospital={hospital=>setSelectedId(hospital.id)} focusLocations={selectedId&&selected?[selected.location]:hospitals.map(h=>h.location)} focusKey={selectedId?`hospital-${selectedId}`:'hospital-all'} initialCenter={selected?.location} initialZoom={14}/></section><aside className="hospital-directory" aria-label="Directorio de centros médicos">{hospitals.map(h=>{const basedUnits=unitsAtBase(h.id);return <button type="button" className={`hospital-card ${selectedId===h.id?'selected':''}`} key={h.id} onClick={()=>setSelectedId(h.id)}><div className="hospital-icon"><Building2/></div><div className="hospital-card-copy"><strong>{h.shortName||h.name}</strong><span>{h.type} · {h.network}</span><small><MapPin size={12}/>{h.address}</small></div><Badge tone={h.status==='available'?'green':h.status==='full'?'red':'amber'}>{h.status==='available'?'Disponible':h.status==='full'?'Sin cupo':'Demanda alta'}</Badge><div className="hospital-card-footer"><span>{h.capacity||0} cupos simulados</span><span>{h.receivesTransfers?'Urgencias y traslados':'Base de atención local'}</span></div>{basedUnits.length>0&&<div className="hospital-based-units"><Ambulance size={14}/><span>{basedUnits.map(unit=>unit.id).join(' · ')}</span></div>}</button>})}</aside></div></div>
}

export function PublicationsAdminPage(){
  const {db,updatePublication,convertPublication}=usePulse(); const [filter,setFilter]=useState('pending')
  const list=(db.publications||[]).filter(p=>filter==='all'||p.status===filter)
  const verify=id=>updatePublication(id,{status:'verified',verifiedAt:new Date().toISOString()})
  const reject=id=>updatePublication(id,{status:'rejected',rejectedAt:new Date().toISOString()})
  const convert=(id,target)=>{convertPublication(id,target);updatePublication(id,{status:'published',convertedTo:target})}
  return <div className="admin-page"><div className="admin-toolbar admin-toolbar-compact"><select aria-label="Filtrar publicaciones por estado" value={filter} onChange={e=>setFilter(e.target.value)}><option value="pending">Pendientes</option><option value="verified">Verificadas</option><option value="published">Publicadas</option><option value="rejected">Rechazadas</option><option value="all">Todas</option></select></div><div className="publication-admin-grid">{list.map(p=><article className="publication-admin-card" key={p.id}><img src={p.image||'/assets/generated/incidents/accidente-vehicular.webp'} alt=""/><div className="publication-admin-body"><div className="publication-meta"><Badge tone={p.status==='pending'?'amber':p.status==='rejected'?'red':'green'}>{p.status}</Badge><span>{new Date(p.createdAt).toLocaleString('es-CR')}</span></div><h3>{p.title}</h3><p>{p.description}</p><span><MapPin size={14}/>{p.location?.label||'Ubicación demo'}</span>{p.status==='pending'&&<div className="publication-actions"><button className="btn primary small" onClick={()=>verify(p.id)}><CheckCircle2 size={14}/>Verificar</button><button className="btn ghost small danger" onClick={()=>reject(p.id)}><XCircle size={14}/>Rechazar</button></div>}{p.status==='verified'&&<div className="publication-actions"><button className="btn ghost small" onClick={()=>convert(p.id,'incident')}><Siren size={14}/>Crear incidente</button><button className="btn ghost small" onClick={()=>convert(p.id,'alert')}><Radio size={14}/>Crear alerta</button><button className="btn ghost small" onClick={()=>convert(p.id,'risk')}><ShieldAlert size={14}/>Crear riesgo</button></div>}</div></article>)}</div>{!list.length&&<div className="empty"><ClipboardCheck size={30}/><h3>No hay publicaciones en este estado</h3><p>Los reportes comunitarios aparecerán aquí cuando se creen desde Citizen.</p></div>}</div>
}

export function AuditPage(){
  const {db}=usePulse(); const [q,setQ]=useState(''); const logs=(db.auditLogs||[]).slice().reverse().filter(l=>`${l.label} ${l.type}`.toLowerCase().includes(q.toLowerCase()))
  return <div className="admin-page"><div className="admin-toolbar admin-toolbar-compact"><input aria-label="Buscar en auditoría" placeholder="Buscar acción..." value={q} onChange={e=>setQ(e.target.value)}/></div><section className="admin-panel audit-panel"><div className="audit-head"><FileText/><strong>{logs.length} eventos registrados</strong></div><div className="audit-list">{logs.map(l=><div key={l.id}><div className="audit-icon"><Activity size={15}/></div><div><strong>{l.label}</strong><span>{new Date(l.at).toLocaleString('es-CR')}</span></div><small>{l.type}</small></div>)}</div></section></div>
}

export function ScenariosPage(){
  const {db,loadScenario}=usePulse(); const [loaded,setLoaded]=useState('')
  return <div className="admin-page"><div className="scenario-grid">{(db.scenarios||[]).map(s=><article className="scenario-card" key={s.id}><div className="scenario-icon"><Siren/></div><span className="eyebrow">ESCENARIO DEMO</span><h3>{s.name}</h3><p>{s.description}</p><div className="scenario-flow"><span>Incidente</span><b>→</b><span>Despacho</span><b>→</b><span>Respuesta</span></div><button className="btn primary" onClick={()=>{loadScenario(s.id);setLoaded(s.id)}}><Play size={15}/>{loaded===s.id?'Escenario cargado':'Cargar escenario'}</button></article>)}</div></div>
}
