import { useState } from 'react'
import { Activity, Ambulance, Building2, CheckCircle2, ClipboardCheck, FileText, MapPin, Play, Radio, ShieldAlert, Siren, Truck, XCircle } from 'lucide-react'
import { usePulse } from '../../context/PulseContext'
import { Badge, StatCard } from '../../components/Common'

export function UnitsPage(){
  const {db, returnUnit}=usePulse(); const [filter,setFilter]=useState('all')
  const units=db.units.filter(u=>filter==='all'||u.status===filter)
  return <div className="admin-page"><div className="admin-toolbar"><div><span>RECURSOS</span><h2>Unidades de respuesta</h2><p>Estado operativo de ambulancias, rescate, bomberos y seguridad dentro de la simulación.</p></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todas</option><option value="available">Disponibles</option><option value="en_route">En ruta</option><option value="on_scene">En sitio</option><option value="transporting">Trasladando</option><option value="returning">Regresando</option></select></div><div className="admin-stats"><StatCard label="Disponibles" value={db.units.filter(u=>u.status==='available').length} icon={Ambulance} tone="green"/><StatCard label="En ruta" value={db.units.filter(u=>u.status==='en_route').length} icon={Radio} tone="amber"/><StatCard label="En sitio" value={db.units.filter(u=>u.status==='on_scene').length} icon={ShieldAlert}/><StatCard label="Trasladando" value={db.units.filter(u=>u.status==='transporting').length} icon={Truck} tone="red"/></div><section className="admin-panel"><div className="unit-management-grid">{units.map(u=><article className="resource-unit-card" key={u.id}><div className="resource-unit-head"><div className="resource-unit-icon"><Ambulance size={20}/></div><div><strong>{u.id}</strong><span>{u.type}</span></div><Badge tone={u.status==='available'?'green':u.status==='en_route'||u.status==='transporting'?'amber':'blue'}>{u.status.replaceAll('_',' ')}</Badge></div><dl><div><dt>Incidente</dt><dd>{u.assignedIncident||'Base'}</dd></div><div><dt>Tripulación</dt><dd>{u.crew||'—'}</dd></div><div><dt>Capacidades</dt><dd>{(u.capabilities||[]).join(', ')}</dd></div></dl>{u.status==='at_hospital'&&<button className="btn ghost small" onClick={()=>returnUnit(u.id)}>Iniciar regreso a base</button>}{u.status==='on_scene'&&<span className="resource-note">Lista para traslado desde el sitio.</span>}</article>)}</div></section></div>
}

export function HospitalsPage(){
  const {db}=usePulse();
  return <div className="admin-page"><div className="admin-toolbar"><div><span>DESTINOS DE TRASLADO</span><h2>Hospitales y capacidad</h2><p>Recursos hospitalarios simulados para decidir el destino de un traslado.</p></div></div><div className="hospital-grid">{(db.hospitals||[]).map(h=><article className="hospital-card" key={h.id}><div className="hospital-icon"><Building2/></div><div><strong>{h.name}</strong><span>{h.status==='available'?'Capacidad disponible':h.status==='full'?'Sin capacidad':'Demanda alta'}</span></div><Badge tone={h.status==='available'?'green':h.status==='full'?'red':'amber'}>{h.status}</Badge><div className="capacity-bar"><i style={{width:`${Math.min(100,Math.max(12,(h.capacity||10)/30*100))}%`}}/></div><small>{h.capacity||0} cupos simulados · {h.location?.lat?.toFixed?.(4)}, {h.location?.lng?.toFixed?.(4)}</small></article>)}</div></div>
}

export function PublicationsAdminPage(){
  const {db,updatePublication,convertPublication}=usePulse(); const [filter,setFilter]=useState('pending')
  const list=(db.publications||[]).filter(p=>filter==='all'||p.status===filter)
  const verify=id=>updatePublication(id,{status:'verified',verifiedAt:new Date().toISOString()})
  const reject=id=>updatePublication(id,{status:'rejected',rejectedAt:new Date().toISOString()})
  const convert=(id,target)=>{convertPublication(id,target);updatePublication(id,{status:'published',convertedTo:target})}
  return <div className="admin-page"><div className="admin-toolbar"><div><span>INTELIGENCIA COMUNITARIA</span><h2>Publicaciones ciudadanas</h2><p>Revisa reportes comunitarios y decide si deben convertirse en incidentes, alertas o zonas de riesgo.</p></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="pending">Pendientes</option><option value="verified">Verificadas</option><option value="published">Publicadas</option><option value="rejected">Rechazadas</option><option value="all">Todas</option></select></div><div className="publication-admin-grid">{list.map(p=><article className="publication-admin-card" key={p.id}><img src={p.image||'/assets/generated/incidents/accidente-vehicular.webp'} alt=""/><div className="publication-admin-body"><div className="publication-meta"><Badge tone={p.status==='pending'?'amber':p.status==='rejected'?'red':'green'}>{p.status}</Badge><span>{new Date(p.createdAt).toLocaleString('es-CR')}</span></div><h3>{p.title}</h3><p>{p.description}</p><span><MapPin size={14}/>{p.location?.label||'Ubicación demo'}</span>{p.status==='pending'&&<div className="publication-actions"><button className="btn primary small" onClick={()=>verify(p.id)}><CheckCircle2 size={14}/>Verificar</button><button className="btn ghost small danger" onClick={()=>reject(p.id)}><XCircle size={14}/>Rechazar</button></div>}{p.status==='verified'&&<div className="publication-actions"><button className="btn ghost small" onClick={()=>convert(p.id,'incident')}><Siren size={14}/>Crear incidente</button><button className="btn ghost small" onClick={()=>convert(p.id,'alert')}><Radio size={14}/>Crear alerta</button><button className="btn ghost small" onClick={()=>convert(p.id,'risk')}><ShieldAlert size={14}/>Crear riesgo</button></div>}</div></article>)}</div>{!list.length&&<div className="empty"><ClipboardCheck size={30}/><h3>No hay publicaciones en este estado</h3><p>Los reportes comunitarios aparecerán aquí cuando se creen desde Citizen.</p></div>}</div>
}

export function AuditPage(){
  const {db}=usePulse(); const [q,setQ]=useState(''); const logs=(db.auditLogs||[]).slice().reverse().filter(l=>`${l.label} ${l.type}`.toLowerCase().includes(q.toLowerCase()))
  return <div className="admin-page"><div className="admin-toolbar"><div><span>TRAZABILIDAD</span><h2>Auditoría operacional</h2><p>Cada acción importante de la simulación deja un registro para explicar el flujo durante la presentación.</p></div><input placeholder="Buscar acción..." value={q} onChange={e=>setQ(e.target.value)}/></div><section className="admin-panel audit-panel"><div className="audit-head"><FileText/><strong>{logs.length} eventos registrados</strong></div><div className="audit-list">{logs.map(l=><div key={l.id}><div className="audit-icon"><Activity size={15}/></div><div><strong>{l.label}</strong><span>{new Date(l.at).toLocaleString('es-CR')}</span></div><small>{l.type}</small></div>)}</div></section></div>
}

export function ScenariosPage(){
  const {db,loadScenario}=usePulse(); const [loaded,setLoaded]=useState('')
  return <div className="admin-page"><div className="admin-toolbar"><div><span>SIMULADOR ACADÉMICO</span><h2>Escenarios de demostración</h2><p>Carga un caso completo para demostrar el ciclo operativo sin depender de datos externos.</p></div></div><div className="scenario-grid">{(db.scenarios||[]).map(s=><article className="scenario-card" key={s.id}><div className="scenario-icon"><Siren/></div><span className="eyebrow">ESCENARIO DEMO</span><h3>{s.name}</h3><p>{s.description}</p><div className="scenario-flow"><span>Incidente</span><b>→</b><span>Despacho</span><b>→</b><span>Respuesta</span></div><button className="btn primary" onClick={()=>{loadScenario(s.id);setLoaded(s.id)}}><Play size={15}/>{loaded===s.id?'Escenario cargado':'Cargar escenario'}</button></article>)}</div></div>
}
