import { useMemo, useState } from 'react'
import { AlertTriangle, MapPinned, Plus, ShieldAlert, Trash2 } from 'lucide-react'
import { usePulse } from '../../context/PulseContext'
import GeoMap from '../../components/GeoMap'
import { Badge, InlineNotice } from '../../components/Common'

const categoryLabels={traffic_accident:'Accidentes vehiculares',fire:'Incendios',flood:'Inundación',road_hazard:'Riesgo vial',landslide:'Deslizamiento',electrical:'Riesgo eléctrico'}
const severityLabels={critical:'Crítico',high:'Alto',medium:'Medio',low:'Bajo'}
const empty={title:'',area:'',severity:'high',category:'traffic_accident',reports:1,radiusM:220,description:'',location:null}

export default function RiskZonesPage(){
  const {db,addRiskZone,updateRiskZone,deleteRiskZone}=usePulse(); const riskZones=db.riskZones||[]
  const [form,setForm]=useState(empty),[selectedId,setSelectedId]=useState(null),[placing,setPlacing]=useState(false),[moving,setMoving]=useState(false),[notice,setNotice]=useState(null)
  const critical=riskZones.filter(z=>['critical','high'].includes(z.severity)).length
  const historical=db.historicalIncidents||[]
  const clusters=useMemo(()=>riskZones.map(z=>({...z,historical:historical.filter(h=>Math.abs(h.lat-z.location.lat)<.004&&Math.abs(h.lng-z.location.lng)<.004).length})),[riskZones,historical])
  const select=z=>{setSelectedId(z.id);setForm({...z});setPlacing(false);setMoving(false);setNotice(null)}
  const fresh=()=>{setSelectedId(null);setForm(empty);setPlacing(true);setMoving(false);setNotice({tone:'info',text:'Haz clic en el mapa para colocar la nueva zona.'})}
  const save=e=>{e.preventDefault();if(!form.location){setNotice({tone:'error',text:'Selecciona primero un punto en el mapa.'});return} if(selectedId){updateRiskZone(selectedId,form);setNotice({tone:'success',text:'Zona de riesgo actualizada.'})}else{const z=addRiskZone(form);setSelectedId(z.id);setNotice({tone:'success',text:'Zona de riesgo registrada.'})} setMoving(false)}
  const mapClick=ll=>{if(placing||!form.location){setForm(v=>({...v,location:ll}));setPlacing(false);setNotice({tone:'success',text:'Ubicación seleccionada. Completa los datos y guarda la zona.'})}}
  const mapRiskZones=form.location&&!selectedId?[...riskZones,{id:'risk-draft',...form,reports:form.reports||1}]:riskZones
  return <div className="admin-page risk-page-v4">
    <div className="risk-overview">
      <div className="risk-stats-row"><div><ShieldAlert/><strong>{riskZones.length}</strong><span>Zonas registradas</span></div><div><AlertTriangle/><strong>{critical}</strong><span>Prioridad alta/crítica</span></div><div><MapPinned/><strong>{historical.length}</strong><span>Eventos históricos GIS</span></div></div>
      <div className="admin-toolbar admin-toolbar-compact"><button className="btn primary" onClick={fresh}><Plus size={16}/>Registrar zona en mapa</button></div>
    </div>
    {notice&&<InlineNotice tone={notice.tone}>{notice.text}</InlineNotice>}

    <div className="geo-editor-workspace risk-editor-v4"><section className="admin-panel geo-editor-map"><div className="map-edit-banner">{placing?'Haz clic sobre el mapa para colocar el nuevo punto peligroso':moving?'Arrastra el punto seleccionado para cambiar su ubicación':'Selecciona una zona existente o crea una nueva'}</div><GeoMap incidents={db.incidents.filter(i=>!['resolved','cancelled'].includes(i.status))} units={db.units} alerts={db.alerts} riskZones={mapRiskZones} hospitals={db.hospitals||[]} historicalIncidents={historical} selectedId={selectedId||'risk-draft'} onSelectRiskZone={z=>z.id!=='risk-draft'&&select(z)} onMapClick={mapClick} draggableRiskId={moving?selectedId:null} onMoveRiskZone={(id,ll)=>{updateRiskZone(id,{location:ll});setForm(v=>({...v,location:ll}))}}/></section>
      <form className="admin-panel risk-form geo-form-v4" onSubmit={save}><div className="panel-title"><Plus/><h3>{selectedId?'Editar zona peligrosa':'Registrar zona peligrosa'}</h3></div><label>Nombre del punto<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Ej. Intersección con colisiones frecuentes"/></label><label>Zona / referencia<input required value={form.area} onChange={e=>setForm({...form,area:e.target.value})} placeholder="Ej. El Roble — corredor demo"/></label><div className="form-grid"><label>Tipo<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option value="traffic_accident">Accidentes vehiculares</option><option value="fire">Incendios</option><option value="flood">Inundación</option><option value="road_hazard">Riesgo vial</option><option value="landslide">Deslizamiento</option><option value="electrical">Riesgo eléctrico</option></select></label><label>Nivel<select value={form.severity} onChange={e=>setForm({...form,severity:e.target.value})}><option value="critical">Crítico</option><option value="high">Alto</option><option value="medium">Medio</option><option value="low">Bajo</option></select></label><label>Reportes asociados<input min="1" type="number" value={form.reports} onChange={e=>setForm({...form,reports:Number(e.target.value)})}/></label><label>Radio ({form.radiusM||220} m)<input min="80" max="900" step="20" type="range" value={form.radiusM||220} onChange={e=>setForm({...form,radiusM:Number(e.target.value)})}/></label></div><label>Descripción<textarea value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Describe por qué se considera peligroso este punto..."/></label><div className="geo-coordinates"><span>Coordenadas</span><strong>{form.location?`${form.location.lat.toFixed(5)}, ${form.location.lng.toFixed(5)}`:'Haz clic en el mapa'}</strong></div><div className="geo-form-actions"><button className="btn primary"><Plus size={16}/>{selectedId?'Guardar cambios':'Registrar zona'}</button>{selectedId&&<button type="button" className="btn ghost" onClick={()=>setMoving(v=>!v)}>{moving?'Finalizar movimiento':'Mover punto'}</button>}{selectedId&&<button type="button" className="btn ghost danger" onClick={()=>{deleteRiskZone(selectedId);fresh();setNotice({tone:'success',text:'Zona eliminada del escenario.'})}}><Trash2 size={15}/>Eliminar</button>}</div></form></div>

    <section className="admin-panel"><div className="panel-title"><AlertTriangle/><h3>Prioridades registradas</h3><Badge tone="blue">Cruce con historial simulado</Badge></div><div className="risk-zone-list v4">{clusters.map(zone=><button type="button" key={zone.id} onClick={()=>select(zone)}><img src={zone.image} alt=""/><div><div className="risk-zone-tags"><Badge tone={zone.severity==='critical'?'red':zone.severity==='high'?'amber':'blue'}>{severityLabels[zone.severity]}</Badge><span>{categoryLabels[zone.category]||zone.category}</span></div><strong>{zone.title}</strong><span>{zone.area}</span><small>{zone.reports} reportes · {zone.historical} eventos históricos cercanos</small></div></button>)}</div></section>
  </div>
}
